import "./globals.css";
import { ThemeProvider } from "@/hooks/useTheme";

export const metadata = {
  title: "InventoRiz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="fr">
      <body className="bg-slate-100">
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
